services:
  adameds-rekamedis:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/rekam-medis:dev
    container_name: api-adameds-rekam-medis
    ports:
      - 8087:8087
    restart: always
    networks:
      - rekamedis-network
    environment:
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      API_BASE: ${API_BASE}
      API_VERSION: ${API_VERSION}
    # volumes:
    #   - type: bind
    #     source: /home/engineer/adameds/.env.vault
    #     target: /adameds-rekam-medis/.env.vault
networks:
  rekamedis-network:
    driver: bridge
