services:
  adameds-rekamedis:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/rekamedis:dev
    container_name: adameds-Rekamedis
    ports:
      - 8087:8087
    restart: always
    networks:
        - rekamedis-network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DIALECT: ${DB_DIALECT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}

      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: ${default}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${6379}
      REDIS_DATABASE: ${REDIS_DATABASE}
    volumes:
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-rekam-medis/public.key
  
  mongodb:
    container_name: mongodb-rekamedis
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - 27017:27017 
    volumes:
      - type: volume
        source: mongo-volume
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}   
networks:
  rekamedis-network:
    driver: bridge
volumes:
  mongo-volume: {}